### PR TITLE
Fix bugs in Makefile for newer operating systems

### PR DESCRIPTION
**Pull request by Buggem**
Follow up to my issue [#578](https://github.com/LIJI32/SameBoy/issues/578#issue-2060974860). A fix for 2 bugs I was facing when I built SameBoy on macOS Sonama.

### CODE REVIEW

**Comment by Buggem** [comment]
Note: this patch is only intended to be a fix if worse comes to worse, as it requires a password. But as it is only for building, this might not matter as much.

**Comment by LIJI32** [comment]
This isn't very future (or past) proof, as the user might only have the 12.x or 14.x SDKs, `grep "[0-9]\."` is probably a better solution to get the latest numbered SDK.

**Comment by Buggem** [comment]
@LIJI32 updated as per code example

**Comment by LIJI32** [comment]
I actually missed the `$(shell sudo xcode-select -s /Applications/Xcode.app/Contents/Developer)` line, why is this needed? It runs even if the previous line successfully found a Sysroot, and the following line will work regardless of the path reset.

**Pull request merged**
