### PR TITLE
Update libretro dependencies

### PR DESCRIPTION
**Pull request by RobLoach**
This updates the Makefile dependency chain to build rgblink and all when needed. It's missing `flex`, which seems to be a dependency of rgbasm/link, but we'll figure that out later.

### CODE REVIEW

**Comment by RobLoach** [comment]
Hmm, not sure about this one. Would love some thoughts....

**Comment by RobLoach** [comment]
@fr500 I've seen you in here a few times. What do you think about building the dependencies through the Makefile like this?

**Comment by fr500** [comment]
I really don't know, I know TA doesn't like dependencies and the current workflow is fine (we have a branch on our fork that I update like... once a month)

**Comment by RobLoach** [comment]
Sounds good.

**Pull request closed without merging**
