### PR TITLE
Resolve various deprecation warnings.

### PR DESCRIPTION
**Pull request by jverkoey**
- fileName -> fileURL
- NSFullScreenWindowMask -> NSWindowStyleMaskFullScreen
- NSFileHandlingPanelOKButton -> NSModalResponseOK
- NSPNGFileType -> NSBitmapImageFileTypePNG

## TODO

- [x] Revert the nil comparison changes.

Pre-work for #324

### CODE REVIEW

**Comment by LIJI32** [comment]
Two of these warnings are conscious design and style choices:
*  The use of filenames over URL: While long deprecated, the NSString based APIs are cleaner than the NSURL based alternatives, as NSURL doesn't provide any benefits while requiring lengthy conversions between NSURL and NSString.
* Implicit conversion between pointers and bools is a style choice; since when did that even become a warning?

As for the rest – good catches, I never remember which of these symbols are the non-deprecated ones.

**Comment by jverkoey** [comment]
> Implicit conversion between pointers and bools is a style choice; since when did that even become a warning?

Ah this is a style habit for me from the [Google Objective-C style guide](https://google.github.io/styleguide/objcguide.html#bool-pitfalls); I don't feel strongly about it here though because we're not interacting with BOOL, so am happy to revert that change. I'll add a TODO to the PR description.

**Comment by jverkoey** [comment]
> The use of filenames over URL: While long deprecated, the NSString based APIs are cleaner than the NSURL based alternatives, as NSURL doesn't provide any benefits while requiring lengthy conversions between NSURL and NSString.

Agreed the string-based APIs had historically provided better facilities for working with paths. macOS 10.6 introduced new APIs on NSURL for working with paths, so in many cases the APIs are comparable now.

```objc
[[self.fileName stringByDeletingPathExtension] stringByAppendingPathExtension:@"ram"]
```

becomes

```objc
[[self.fileURL URLByDeletingPathExtension] URLByAppendingPathExtension:@"ram"].path
```

The need to invoke `path` to convert to a string can be made less obtrusive by using property notation, and I've also made the UTF8String invocations follow a similar pattern (from `[self.fileName UTF8String]` to `self.fileURL.path.UTF8String` which is intended to improve readability by removing a layer of `[ ]` brackets.

I'm siding on the side of resolving the deprecation warnings for this, but if you feel strongly about keeping the deprecated APIs in place I will defer to your call.

**Comment by jverkoey** [comment]
Changes to nil checks have been reverted.

**Comment by jverkoey** [comment]
Another proposal for the fileName -> fileURL change is that I'd be happy to make a helper method for changing the file's extension if clarity / verboseness is the primary concern.

**Pull request merged**
