### PR TITLE
libretro: Android update

### PR DESCRIPTION
**Pull request by webgeek1234**
Needed for ndk r20

I didn't realize the libretro fork only existed for the buildbot commit until after I had submitted this pr there. Once this is merged here, I'll get someone to clean up downstream.

### CODE REVIEW

**Comment by LIJI32** [comment]
Should this flag even be there? I don't use *any* C++ code in SameBoy.

**Comment by webgeek1234** [comment]
In that case, no. With no c++ code, the flag should just code away.

**Comment by LIJI32** [comment]
I'm not sure how the Android build system works, will removing this line entirely break anything?

**Comment by webgeek1234** [comment]
Nah, it's not necessary. Several libretro cores are pure ANSI C and don't have that flag.

**Comment by LIJI32** [comment]
Good, so it's gone now. :)

**Pull request merged**
