### PR TITLE
Update from downstream

### PR DESCRIPTION
**Pull request by fr500**
@LIJI32 small updates to the libretro core

### CODE REVIEW

**Comment by LIJI32** [comment]
SameBoy doesn't use C++, why would you even need to specify STL?

**Comment by fr500** [comment]
@webgeek1234 can you answer this one please?

**Comment by webgeek1234** [comment]
I don't have time atm to look myself, but I believe if you look back through the PRs here, the android stuff was already talked about and fixed differently from what I had merged to the downstream libretro fork. That's why I said a few times that the fork needed FPed, but I don't think it ever happened.

**Comment by fr500** [comment]
Oh, sorry about that so I'll remove that commit

**Pull request merged**
