### PR TITLE
Ready to merge: SGB in the libretro core

### PR DESCRIPTION
**Pull request by fr500**
I tried to hookup sgb but it either crashes or stops at a garbled sgb screen, I think the geometry may be different.

let me know if you have any pointers :)

### CODE REVIEW

**Comment by fr500** [comment]
@LIJI32 this is working fully now and the commits only touch libretro code.

**Comment by LIJI32** [comment]
Does this include support for multiplayer SGB games (like Bomberman)?

**Comment by fr500** [comment]
probably not, I'll check tonight shouldn't be too hard to hook up

**Comment by fr500** [comment]
image

I know my code is a bit redundant, nitpicky but I prefer it like that.
I want to show only the enabled controllers on the frontend, and I want to poll only what is required (should save a few ms here and there that way)

So I set 2p descriptors for linked mode, 1p descriptors for all single modes, and 4p descriptors for SGB

**Pull request merged**
